version: 0.2
phases:
  install:
    runtime_version:
      python: 3.10
  pre_build:
    commands:
      - pip install -r requirements.txt
#      - python app.py
  build:
    commands:
      - python app.py
      - # Get its PID
      - PID= ps -ef | grep python
        # Wait for 2 seconds
      - sleep 2
        # Kill it
      - kill $PID

  post_build:
    commands:
      - aws s3 sync . S3://bucket-name/key-name --acl public-read


artifacts:
  files:
    - '**/*'

#    - target/my-app-1.0-SNAPSHOT.jar
#    - appspec.yml
#  discard-paths: yes

